root = "."
tmp_dir = "tmp" 

[build]
	cmd = "GOFLAGS=-buildvcs=false go build -o ./tmp/main ./cmd/web"
	bin = "./tmp/main"
	# Watch these directories for changes
	include_dir = ["internal", "web/templates", "."]
	exclude_dir = ["tmp", "vendor", "data", "web/static"]
	include_ext = ["go", "tpl", "tmpl", "html", "css", "js", "sql"] 
	exclude_file = []
	log = "air_build.log"
	delay = 1000

[log]
	time = true

[misc]
	clean_on_exit = true

[screen]
	clear_on_rebuild = true
