services:
  app:
    build:
      context: .
      target: development
    volumes:
      - ./:/app
      - ./data:/app/data
    environment:
      - PORT=$PORT
      - AIR_PROXY_PORT=$AIR_PROXY_PORT
      - DB_PATH=$DB_PATH
    ports:
      - $PORT:$PORT
      - $AIR_PROXY_PORT:$AIR_PROXY_PORT
